# Generated by Django 5.0.3 on 2024-04-24 09:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='join_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
